### PR TITLE
Add support to universal framework

### PR DESCRIPTION
**Pull request by cojoj**
I think that way would be easier... This PR can replace #7

### CODE REVIEW

**Comment by cojoj** [comment]
After your changes I think this PR can be closed, right?

**Comment by czechboy0** [comment]
Yup, I'm still trying to get both iOS and OS X playgrounds working in the project.

**Comment by cojoj** [comment]
Are there any problems with this?

**Comment by czechboy0** [comment]
Yeah I'm not sure that having a truly iOS/OSX universal framework is doable. Maybe having them compile on demand as a dependency works, but I can't seem to get it working - build the framework once and have it available from both iOS and OS X playgrounds. It's on a branch [hd/universal_framework](https://github.com/czechboy0/XcodeServerSDK/tree/hd/universal_framework) if you want to take a look.

**Comment by cojoj** [comment]
As far as I can see Argo is importing their framework inside Playground.

**Comment by cojoj** [comment]
- Your playground must be in the same workspace as the project that produces your framework.
- You must have already built your framework. If it is an iOS framework, it must be built for a 64-bit run destination (e.g. iPhone 5s).
- You must have an active scheme which builds at least one target (that target's build location will be used in the framework search path for the playground).
- Your "Build Location" preference (in advanced "Locations" settings of Xcode) should not be set to "Legacy".
- If your framework is not a Swift framework the "Defines Module" build setting must be set to "Yes".

---

I think that we're missing second point but if you try to build you get errors from `XcodeServerSDK.h`

**Pull request closed without merging**
