### PR TITLE
Add Carthage shield to README

### PR DESCRIPTION
**Pull request by cojoj**
Hmm, I guess @czechboy0  assigned this silently to me in #30 and thanks to a teamwork (kudos @esttorhe) we're officially supporting **Carthage** which has been tested and works pretty nice.

Here's the README update with beautiful **Carthage** shield and updated _Sources_ section.

---

I don't know if you guys will like it but I've created a table covering _features_ which compares `XcodeServerSDK` with official API endpoint/possibilities.

### CODE REVIEW

**Comment by czechboy0** [comment]
Awesome, @cojoj, thanks!

**Comment by czechboy0** [comment]
BTW all of those endpoints that Apple officially supports and we don't we can easily add. Just add a method in `XcodeServer` and possibly a new endpoint in `XcodeServerEndpoints`. It would be nice to support **all** the Apple endpoints plus some. Do you want to create an issue for this? Should be an easy one for anyone with 20mins on their hands. Thanks!

**Comment by cojoj** [comment]
Yeah, I'll create issue for this with a nice bullet list 😉

**Comment by czechboy0** [comment]
Ok, sounds good. I also made a couple of fixes, so base the checklist on the new readme version: https://github.com/czechboy0/XcodeServerSDK/commit/e694947661862b644ed2d662d726dc5633e42eb2

**Pull request merged**
