### PR TITLE
XcodeServerEndpoints.createRequest tests

### PR DESCRIPTION
**Pull request by pmkowal**
Hey, I added three tests for `createRequest` method, but I don't have a clue how to 100% cover the `XcodeServerEndpoints` class.
Please take a look.

Btw. I have one proposition regarding `XcodeServer` class.
I would move the code below (from `sendRequestWithMethod` method) to `createRequest` method, because `createRequest` method can figure out `HTTP.Method` directly from its parameter. What do you think?

``` swift
var allParams = [
    "method": method.rawValue
]

//merge the two params
if let params = params {
    for (key, value) in params {
        allParams[key] = value
    }
}
```

### CODE REVIEW

**Comment by buildasaur** [comment]
## Result of Integration **1**

_Duration_: 1 minute and 5 seconds
_Result_: **Perfect build!** All 48 tests passed. :+1:
_Test Coverage_: 51%.

**Comment by cojoj** [comment]
@pmkowal can you provide a screenshot of test coverage form `XcodeServerEndpoints` class?

**Comment by pmkowal** [comment]
here you go @cojoj:

testcoverage

**Comment by cojoj** [comment]
Nah, the test coverage in code... You know, this fancy indicators showing which lines has been tested 😉

**Comment by pmkowal** [comment]
@cojoj are you concerned with buildasaur result of integration?

**Comment by cojoj** [comment]
Nope, just want to see coverage and give you ans answer to

> but I don't have a clue how to 100% cover the XcodeServerEndpoints class

**Comment by pmkowal** [comment]
Cool, I didn't look at it, thx @cojoj 

linescoverage

**Comment by pmkowal** [comment]
Ok, I know now how to test `authorization` part, but do you have idea how to test `body` part?

**Comment by cojoj** [comment]
Great I was just writing about his **authorization** part but if you know how to solve this good for you! 🍹

Now, the `body` part... It'll be used [mostly] for `POST` actions. In that case you have to provide a `body` parameter to `createRequest()`. To fully check this you'll have to provide a valid JSON and in that case `try` wil pass and everything will succeed. To cover rest you'll have to provide a failbale JSON which will crash `NSJSONSerialization.dataWithJSONObject()`

Hope you get me 😉

**Comment by pmkowal** [comment]
The point is tried to provide failbale JSON, but I couldn't figure it out :smile:, because we can use only `[String: String]` as `body` param.

**Comment by pmkowal** [comment]
@cojoj ...and with `authorization` I would create another instance of `XcodeServerEndpoints` with different config. Do you have other ideas?

**Comment by cojoj** [comment]
Exactly... That's what I've been struggling with too 😕
One way is to provide a **malformed** `String` but right now I can't think of any... Leaving code like this without a coverage is a bummer but I guess right now we have no other choice. Maybe @czechboy0 have a neat solution to this? 😜

---

You can move `XcodeServerEndpoint` to a property and mark it as `var` so later in test cases you can simply replace `config`.

**Comment by cojoj** [comment]
I'd be great if we have read access to `Foundation`... You'd simply check what Apple understands under failable JSON. Right now IDK... ¯_(ツ)_/¯

**Comment by pmkowal** [comment]
> You can move XcodeServerEndpoint to a property and mark it as var so later in test cases you can simply replace config

I was rather thinking of creating another `XcodeServerEndpoints` in this particular method, because replacing `serverConfig` could break other tests imo. The seond thing is we cannot exchange `serverConfig` since it is declared as a `let`.

> I'd be great if we have read access to Foundation... You'd simply check what Apple understands under failable JSON. Right now IDK... ¯_(ツ)_/¯

:grin:

**Comment by cojoj** [comment]
Oh okay... If it's `let` you have to create instance of `XcodeServerEnspoints` for each test case.

**Comment by buildasaur** [comment]
## Result of Integration **2**

_Duration_: 52 seconds
_Result_: **Perfect build!** All 49 tests passed. :+1:
_Test Coverage_: 52%.

**Comment by pmkowal** [comment]
ok @cojoj `authorization` part updated.

**Comment by czechboy0** [comment]
Great stuff, thanks @pmkowal!

**Comment by pmkowal** [comment]
:+1:

**Pull request merged**
