### PR TITLE
Swift 2!

### PR DESCRIPTION
**Pull request by czechboy0**
:tada: @cojoj @pmkowal @esttorhe

### CODE REVIEW

**Comment by esttorhe** [comment]
:tada: yeeessss!!

**Comment by buildasaur** [comment]
## Result of Integration **1**

_Duration_: 1 minute and 19 seconds
_Result_: **Perfect build!** All 69 tests passed. :+1:
_Test Coverage_: 57%.

**Comment by czechboy0** [comment]
screenshot 2015-09-10 22 20 01

**Comment by czechboy0** [comment]
Switch back to `master`, boyz!

**Comment by esttorhe** [comment]
feels good to read those words :)

**Comment by pmkowal** [comment]
:+1:

**Pull request merged**
