### PR TITLE
Fixed missing test classes in the iOS test target.

### LINKED ISSUE #42: Different amount of tests on different platform
@esttorhe, while you were creating targets you told us that both OS X and iOS will use the same test target. Could you explain something to me? (I have no idea how it works)

Right now, when I run tests on iOS I get:
screen shot 2015-06-25 at 13 01 50
Which was fine until I switched to OS X and run tests again which produced something different:
screen shot 2015-06-25 at 13 00 03

---

I wonder if it's normal that different targets shows us different test coverage? If you'll tell me that this is totally normal I'm fine... I just have no experience in this matter and that made me thinking 😉

### PR DESCRIPTION
**Pull request by czechboy0**
@cojoj 

Fixes #42.

### CODE REVIEW

**Comment by cojoj** [comment]
I'm sorry for this oversight... 😶

**Comment by czechboy0** [comment]
No worries.

**Comment by esttorhe** [comment]
> All test match on both infrastructures (ᴡᴀᴛᴄʜ doesn't support tests yet).
> --- @esttorhe - https://github.com/czechboy0/XcodeServerSDK/pull/34#issuecomment-115006273

:dizzy_face: :gun:

**Comment by czechboy0** [comment]
Haha if Buildasaur already supported Xcode 7 AND multiple repositories, all PRs would have been tested and we would have seen the issue. So it's still my fault :wink:

**Pull request merged**
