### PR TITLE
Swift 2

### PR DESCRIPTION
**Pull request by cojoj**
I've updated to missing `guard` statements from #6 and changed the name of branch.

### CODE REVIEW

**Comment by czechboy0** [comment]
It's still not mergeable. I must have pushed after you pulled, sorry. Please pull again from master :(

**Comment by cojoj** [comment]
Got It, wait a sec!

**Comment by cojoj** [comment]
@czechboy0 I've merged those two... Only `.gitignore` had conflicts.

**Comment by czechboy0** [comment]
Cool, I'll look over this later today and will comment/merge. Thanks again!

**Comment by cojoj** [comment]
you still see the issue because github doesn't allow creating PR from `swift-2` to `swift-2` because of name conflict. You'll need to do it manually or I'll have to change the name and create new PR to your `swift-2`.

**Comment by czechboy0** [comment]
You have to click the link to compare across forks: https://www.dropbox.com/s/xn9al8aznlnw9lt/Screenshot%202015-06-16%2008.05.53.png?dl=0

**Pull request closed without merging**
