### PR TITLE
Use CustomStringConvertible for description

### PR DESCRIPTION
**Pull request by drewcrawford**
This yields string interpolation.

Should probably be done elsewhere in this codebase, but this is the one
I need today.

### CODE REVIEW

**Comment by czechboy0** [comment]
Sorry, what is this useful for again? (I'll merge it, I just want to understand the use case first)

**Comment by drewcrawford** [comment]
`CustomStringConvertible` is the artist formerly known as `Printable`.  e.g.

``` swift
let bot : Bot = ...
print("\(bot)") // [Bot MyAwesomeBotName]
```

as opposed to

``` swift
let bot : Bot = ...
print("\(bot)") //XcodeServerSDK.Bot
```

or

``` swift
let bot : Bot = ...
print("\(bot.description()")
```

(which, among other problems, conflicts with the Swift/ObjC convention of having a _property_ called description)

**Comment by czechboy0** [comment]
Ah that's cool, didn't know that!

**Comment by czechboy0** [comment]
Thanks @drewcrawford!

**Pull request merged**
