### PR TITLE
Added support for the last missing keys

### LINKED ISSUE #23: Xcode 7: add new keys
Xcode 7 added new keys to the bot configuration json e.g. `exportsProductFromArchive`, `codeCoveragePreference` and more. Add them in the appropriate objects (both parsing and exporting)

A couple at random:
# `BotConfiguration`
- [x] `codeCoveragePreference`
- [x] `exportsProductFromArchive`
- [x] `deviceSpecification` (WIP: #21).
# `SourceControlBlueprint` (WIP: #22)
- [x] `DVTSourceControlWorkspaceBlueprintRemoteRepositoryTrustSelfSignedCertKey`
- [x] `DVTSourceControlWorkspaceBlueprintRemoteRepositoryTrustedCertFingerprintKey`

### PR DESCRIPTION
**Pull request by czechboy0**
Fixed #23.

### CODE REVIEW

**Comment by czechboy0** [comment]
Aight, with this, we're pretty much Xcode 7 API compatible. Wow.

**Comment by czechboy0** [comment]
Just FYI, @cojoj and @esttorhe.

**Comment by esttorhe** [comment]
:tada:

**Comment by cojoj** [comment]
🎈

**Pull request merged**
