### PR TITLE
[WIP]: Added ReactiveCocoa-fied API Calls

### PR DESCRIPTION
**Pull request by czechboy0**
Now all public API calls can be asked for a `SignalProducer` instead of just calling it immediately and passing a completion block.
# Example

When getting the names of your bots, in addition to the existing call

``` swift
server.getBots { (bots, error) -> ()
    if let bots = bots {
        print("My Bots: \(bots.map { $0.name })")
    }
}
```

you can instead call

``` swift
server.getBots()
.map { $0.name }
.start(Event.sink(
                error: { print("Error: \($0)") },
                next: { print("My Bots Names: \($0)") }
            ))
```
# Waiting For
- [x] https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2189 Being merged and there being a Podspec with this Swift 2 version.
- [x] Creating some tests for this (might be a good opportunity to start #105)
- [ ] Add this target to the main scheme so that it gets tested
- [ ] Fixing podspec to add RAC as a dependency to our RAC subspec

### CODE REVIEW

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 1 minute and 21 seconds
*Result*: **Perfect build!** All 69 tests passed. :+1:
*Test Coverage*: 57%.

**Comment by cojoj** [comment]
@czechboy0 example you've provided doesn't look like `RAC` can bring something better 😜 We need to find more **hardcore** example 😁

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 1 minute and 39 seconds
*Result*: All 69 tests passed, but please **fix 1 warning**.
*Test Coverage*: 55%.

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 1 minute and 33 seconds
*Result*: **Perfect build!** All 73 tests passed. :+1:

**Comment by buildasaur** [comment]
Result of Integration **2**
---
*Duration*: 1 minute and 55 seconds
*Result*: **Perfect build!** All 73 tests passed. :+1:
*Test Coverage*: 54%.

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 2 minutes and 9 seconds
*Result*: **Perfect build!** All 73 tests passed. :+1:
*Test Coverage*: 54%.

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 1 minute and 57 seconds
*Result*: **Perfect build!** All 73 tests passed. :+1:
*Test Coverage*: 54%.

**Comment by buildasaur** [comment]
Result of Integration **1**
---
*Duration*: 1 minute and 57 seconds
*Result*: **Perfect build!** All 73 tests passed. :+1:
*Test Coverage*: 54%.

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/494523300873ac12496d00d3a900ed1e/494523300873ac12496d00d3a9014cfd)

_Duration_: 1 minute and 38 seconds
_Result_: **Perfect build!** All 73 tests passed. :+1:
_Test Coverage_: 54%.

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/9dbf435dacd6a870f84de9a7cf024acb/9dbf435dacd6a870f84de9a7cf026e99)

_Duration_: 1 minute and 59 seconds
_Result_: **8 errors, failing state: build-errors**

**Comment by buildasaur** [comment]
## Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/9dbf435dacd6a870f84de9a7cf024acb/9dbf435dacd6a870f84de9a7cf04283e)

_Duration_: 2 minutes and 16 seconds
_Result_: **1 error, failing state: build-errors**

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/dde65e358bed56b12abd92c2440090f6/dde65e358bed56b12abd92c24400933e)

_Duration_: 2 minutes and 29 seconds
_Result_: **3 errors, failing state: build-errors**

**Pull request closed without merging**
